In [6]:
''' Rarely needed calculations (Optional)

    Calculate tables if Fixtures changes(sys.argv[1] == 'full')
    
    Sources:    '{folder}in/Fixtures.csv'
                '{folder}in/Teams.csv'
                f'{folder}in/Table_FPL.csv'
                f'{folder}in/Players.csv'
                
    Writes:    'in/Team_fixtures.csv'
                'in/Team_opponent_team.csv'
                'in/Team_played_fixtures.csv'
                'in/Team_upcoming_fixtures.csv'
                'mid/Team_home.csv'
                'mid/Team_scored.csv'

                'in/Player_fixtures.csv'
                'in/Player_opponent_team.csv'
                'in/Player_played_fixtures.csv'
                'in/Player_upcoming_fixtures.csv'
                'mid/Player_home.csv'
                
                'mid/Team_scores.txt'
                

    
'''



import pandas as pd
import numpy as np
from pathlib import Path
from Brr_functions import no_lists, to_lists, del_empty_col, no_last_GW
import constti

# DATA input
year = ''
if year=='': folder = ''
else: folder = f'history/{year}/'

Fixtures = pd.read_csv(Path(f'{folder}in/Fixtures.csv'))
Teams = pd.read_csv(Path(f'{folder}in/Teams.csv'))
Table = pd.read_csv(Path(f'{folder}in/Table_FPL.csv'))
Players = pd.read_csv(Path(f'{folder}in/Players.csv'))


# Team_all, 
Team_all = pd.DataFrame()
Team_opponent_team = pd.DataFrame()
for j in range(int(Fixtures['event'].max()),0,-1): 
    '''
        Team_all - contains [number of fixture, home team id, away team id]
        Team_fixtures - contains [number of fixture]
        Team_played_fixtures - contains [number of future fixture], future or empty GW deleted
        Team_upcoming_fixtures - contains [number of played fixture], played or empty GW deleted
        Team_opponent_team - [opponent team id]
    '''

    Team_all['GW'+str(j)] = [Fixtures[((Fixtures['team_a']==i)|(Fixtures['team_h']==i))&(Fixtures['event']==j)]\
    [['id', 'team_h', 'team_a']].values for i in range(1, len(Teams)+1)]

    Team_opponent_team['GW'+str(j)] = [[pd.DataFrame(Team_all.at[i,'GW'+str(j)]).loc[:,1:2].values[v][0]\
    if pd.DataFrame(Team_all.at[i,'GW'+str(j)]).loc[:,1:2].values[v][0] != i+1\
    else pd.DataFrame(Team_all.at[i,'GW'+str(j)]).loc[:,1:2].values[v][1]\
    for v in range(len(pd.DataFrame(Team_all.at[i,'GW'+str(j)])))] for i in Team_all.index]
    

Team_opponent_team = no_lists(Team_opponent_team[Team_opponent_team.columns[::-1]])

Team_fixtures = Team_all.applymap(lambda x: [x[i][0] for i in range(len(x))])
Team_fixtures = no_lists(Team_fixtures[Team_fixtures.columns[::-1]])
    
#calculating home/away table with 1/0 and NaN
Team_home = no_lists(Team_all.applymap(lambda x: list(x))).applymap(lambda x: np.nan if type(x)==float else x[1]-1).\
apply(lambda x: x==list(range(len(Team_all)))).applymap(lambda x: 1 if x else 0)\
+no_lists(Team_fixtures)-no_lists(Team_fixtures)#to add NaN

Team_home = Team_home[Team_home.columns[::-1]]#making right order



Team_scores = pd.DataFrame()
for j in range(int(Fixtures['event'].max()),0,-1): 
    Team_scores['GW'+str(j)] = [Fixtures[((Fixtures['team_a']==i)|(Fixtures['team_h']==i))&(Fixtures['event']==j)]\
    [['team_h_score','team_a_score']].values for i in range(1, len(Teams)+1)]
Team_scores = Team_scores[Team_scores.columns[::-1]]

#TSS = Team_scores

Team_scored = (no_lists(Team_scores.applymap(lambda x: list(x)))\
.applymap(lambda x:np.nan if type(x)==float else x[0])*Team_home) +\
(no_lists(Team_scores.applymap(lambda x: list(x)))\
.applymap(lambda x:np.nan if type(x)==float else x[1])*(1-Team_home))
    
del_empty_col(Team_fixtures)

no_lists(Team_fixtures)

del_empty_col(Team_scored)

#Same as in "medium"
Team_played_fixtures = Team_fixtures.applymap(lambda x: np.nan if np.isnan(x) else x \
if Fixtures[Fixtures['id']==x]['finished'].iloc[0] else np.nan)
Team_upcoming_fixtures = Team_fixtures.applymap(lambda x: np.nan if np.isnan(x) else x \
if Fixtures[Fixtures['id']==x]['finished'].iloc[0]==False else np.nan)








Player_all = pd.DataFrame()
Player_fixtures = pd.DataFrame(columns = Team_fixtures.columns)
Player_upcoming_fixtures = pd.DataFrame(columns = Team_upcoming_fixtures.columns)
Player_opponent_team = pd.DataFrame(columns = Team_opponent_team.columns)
if  not Table.empty:
    lastGW = Table['round'].max()
    for j in range(lastGW,0,-1):

        Player_all['GW'+str(j)] = [Table[(Table['element']==i)&\
        (Table['round']==j)][['fixture', 'opponent_team', 'minutes']].values for i in Players['id']]
Player_all = no_lists(Player_all[Player_all.columns[::-1]])


x = pd.DataFrame(np.nan, index=Player_all.index, columns=Team_fixtures.columns)
Player_played_fixtures = Player_all.applymap(lambda x: x[0] if type(x) in {list, np.ndarray} else np.nan)
Player_minutes = Player_all.applymap(lambda x: x[2] if type(x) in {list, np.ndarray} else np.nan)
Player_upcoming_fixtures = x.apply(lambda y: Team_upcoming_fixtures.iloc[Players.at[y.name,'Team number']-1], axis=1)
Player_fixtures = x.apply(lambda x: Team_fixtures.iloc[Players.at[x.name,'Team number']-1], axis=1)
Player_fixtures[Player_played_fixtures.columns] = Player_played_fixtures
Player_played_fixtures = Player_fixtures.applymap(lambda x: np.nan if np.isnan(x) else x \
if Fixtures[Fixtures['id']==x]['finished'].iloc[0] else np.nan) #adding empty columns for foture matches
Player_fixtures[f'GW{lastGW}'] = [Player_upcoming_fixtures[f'GW{lastGW}'][i] \
if np.isnan(Player_played_fixtures[f'GW{lastGW}'][i]) else Player_played_fixtures[f'GW{lastGW}'][i] \
for i in range(len(Players))]

Player_opponent_team = x.apply(lambda x: Team_opponent_team.iloc[Players.at[x.name,'Team number']-1], axis=1)
#Opponents played against
Pot = no_last_GW(Player_all.applymap(lambda x: x[1] if type(x) in {list, np.ndarray} else np.nan))
Player_opponent_team[Pot.columns]  = Pot[Pot.columns]
#Player_opponent_teamX = Pot.merge(Player_opponent_teamX)
def Phome(col):
    '''Function for apply to get home/away for players based on home/away of opposed team'''
    return [np.nan if np.isnan(col[i]) else 1 if Team_home.at[int(col[i])-1, col.name]==0 else 0 for i in range(len(col))]
Player_home = Player_opponent_team.apply(Phome, axis=0)




#Writing
Team_fixtures.to_csv(Path('in/Team_fixtures.csv'), index=False)
Team_opponent_team.to_csv(Path('in/Team_opponent_team.csv'), index=False)
Team_played_fixtures.to_csv(Path('in/Team_played_fixtures.csv'), index=False)
Team_upcoming_fixtures.to_csv(Path('in/Team_upcoming_fixtures.csv'), index=False)
Team_home.to_csv(Path('mid/Team_home.csv'), index=False)
Team_scored.to_csv(Path('mid/Team_scored.csv'), index=False)

Player_fixtures.to_csv(Path('in/Player_fixtures.csv'), index=False)
Player_opponent_team.to_csv(Path('in/Player_opponent_team.csv'), index=False)
Player_played_fixtures.to_csv(Path('in/Player_played_fixtures.csv'), index=False)
Player_upcoming_fixtures.to_csv(Path('in/Player_upcoming_fixtures.csv'), index=False)
Player_minutes.to_csv(Path('mid/Player_minutes.csv'), index=False)
Player_home.to_csv(Path('mid/Player_home.csv'), index=False)


Team_scores.to_json(Path('mid/Team_scores.txt'))

'End'

'End'

In [4]:
Player_played_fixtures
Player_minutes

,GW1,GW2,GW3,GW4,GW5,GW6,GW7,GW8,GW9,GW10,...,GW12,GW13,GW14,GW15,GW16,GW17,GW18,GW19,GW19*,GW20
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0
2,0.0,1.0,90.0,90.0,90.0,48.0,0.0,0.0,0.0,45.0,...,0.0,25.0,90.0,0.0,0.0,0.0,90.0,90.0,NaN,90.0
3,90.0,90.0,90.0,90.0,90.0,90.0,86.0,90.0,90.0,90.0,...,90.0,90.0,0.0,0.0,90.0,90.0,90.0,78.0,NaN,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,5.0,0.0,0.0,0.0,0.0,0.0,90.0,NaN,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
639,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,0.0
640,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
641,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,11.0,NaN,0.0
642,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0
643,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0

In [22]:
Team_scored = no_lists(Team_scores.applymap(lambda x: list(x)))\
#.applymap(lambda x:np.nan if type(x)==float else x[0])
Team_scored['GW19*']

0            NaN
1     [nan, nan]
2            NaN
3            NaN
4              2
5            NaN
6            NaN
7            NaN
8              2
9            NaN
10           NaN
11           NaN
12           NaN
13           NaN
14           NaN
15           NaN
16           NaN
17             2
18             2
19           NaN
Name: GW19*, dtype: object

In [21]:
def get_gw_num(col_name):
    '''
        returns num for standart column name 'GW11**' -> 11
        Used by no_lists, to-lists
    '''
    try:
        return int(col_name.replace('GW','').replace('*',''))
    except:
        return -1

def table_increasing(table):
    colN = [get_gw_num(table.columns[i]) for i in range(len(table.columns))]
    colNN = []
    for i in range(len(colN)):
        if colN[i]>-1:
            colNN.append(colN[i])
    colNNN = np.array(colNN[1:]) - np.array(colNN[:-1])
    for i in range(len(colNNN)):
        if colNNN[i]<0:
            return False
    return True

def no_lists(t):
    '''
        removes lists from table adding new column instead
    '''
    
    def GW_insert(table, col_name):
        '''
            insert columns after if column order is increasing or before if decreasing
        '''
            
        if (col_name[:2] == 'GW')&table_increasing(table):
            table.insert(list(table.columns).index(col_name)+1,col_name+'*',None)
            return table
        else:
            table.insert(list(table.columns).index(col_name),col_name+'*',None)
            return table
        
        
    table = t.copy()
    for i in t.index:
        for j in t.columns:
            if type(table.at[i,j]) in {list, np.ndarray}:
                if len(table.at[i,j])==0:
                    table.at[i,j]=None  #''
                elif len(table.at[i,j])==1:
                    table.at[i,j]=table.at[i,j][0]
                elif  len(table.at[i,j])==2:
                    if j+'*' not in table.columns:
                        #table.insert(list(table.columns).index(j),j+'*',None)
                        table = GW_insert(table, j)
                        print(table['GW19*'])
                        table[j+'*'] = [None for _ in range(len(table))]
                    print(table.at[i,j])
                    table.at[i,j+'*'] = table.at[i,j][1]
                    table.at[i,j]=table.at[i,j][0]
                else:#len(table.at[i,j])==3
                    if j+'*' not in table.columns:
                        table = GW_insert(table, j)
                    if j+'**' not in table.columns:
                        table = GW_insert(table, j+'*')
#                     if j+'*' not in table.columns:
#                         table.insert(list(table.columns).index(j),j+'*',None)
#                     if j+'**' not in table.columns:
#                         table.insert(list(table.columns).index(j)-1,j+'**',None)
                    table.at[i,j+'**'] = table.at[i,j][2]
                    table.at[i,j+'*'] = table.at[i,j][1]
                    table.at[i,j]=table.at[i,j][0]
    return table.fillna(np.nan).applymap(lambda x: x if type(x) != str else np.nan if x=='' else x)

display(list(Team_scores['GW19']))
no_lists(Team_scores.applymap(lambda x: list(x))).columns

[array([[3., 0.]]), array([[ 2.,  0.],
        [nan, nan]]), array([[0., 1.]]), array([[ 1.,  0.],
        [nan, nan]]), array([[0., 1.],
        [2., 0.]]), array([[4., 0.]]), array([], shape=(0, 2), dtype=float64), array([[0., 1.],
        [1., 2.]]), array([[2., 0.],
        [2., 0.]]), array([[0., 1.]]), array([[ 0.,  0.],
        [nan, nan]]), array([[4., 0.],
        [2., 0.]]), array([[0., 0.],
        [1., 2.]]), array([[ 3.,  0.],
        [nan, nan]]), array([[1., 3.]]), array([[2., 0.]]), array([[1., 3.]]), array([[2., 3.],
        [2., 1.]]), array([[1., 0.],
        [2., 1.]]), array([[2., 3.]])]

0     None
1     None
2     None
3     None
4     None
5     None
6     None
7     None
8     None
9     None
10    None
11    None
12    None
13    None
14    None
15    None
16    None
17    None
18    None
19    None
Name: GW19*, dtype: object
[array([2., 0.]), array([nan, nan])]
[array([1., 0.]), array([nan, nan])]
[array([0., 1.]), array([2., 0.])]
[array([0., 1.]), array([1., 2.])]
[array([2., 0.]), array([2., 0.])]
[array([0., 0.]), array([nan, nan])]
[array([4., 0.]), array([2., 0.])]
[array([0., 0.]), array([1., 2.])]
[array([3., 0.]), array([nan, nan])]
[array([2., 3.]), array([2., 1.])]
[array([1., 0.]), array([2., 1.])]

Index(['GW1', 'GW2', 'GW3', 'GW4', 'GW5', 'GW6', 'GW7', 'GW8', 'GW9', 'GW10',
       'GW11', 'GW12', 'GW13', 'GW14', 'GW15', 'GW16', 'GW17', 'GW18', 'GW19',
       'GW19*', 'GW20', 'GW21', 'GW22', 'GW23', 'GW24', 'GW25', 'GW26', 'GW27',
       'GW28', 'GW29', 'GW30', 'GW31', 'GW32', 'GW33', 'GW34', 'GW35', 'GW36',
       'GW37', 'GW38'],
      dtype='object')

In [65]:
list([np.asarray([1,2,3])])

[array([1, 2, 3])]

In [15]:
list(Team_scores['GW19'][17]) == Team_scores['GW19'][17]
A = pd.DataFrame({'a': [Team_scores.at[17,'GW19']]})
no_lists(A)

           a*           a
0  [2.0, 1.0]  [2.0, 3.0]

In [9]:
Player_played_fixtures.columns

Index(['GW1', 'GW2', 'GW3', 'GW4', 'GW5', 'GW6', 'GW7', 'GW8', 'GW9', 'GW10',
       'GW11', 'GW12', 'GW13', 'GW14', 'GW15', 'GW16', 'GW17', 'GW18', 'GW19',
       'GW19*', 'GW19**'],
      dtype='object')